#!/usr/bin/env bash
# Launch backend + Next.js frontend together. Ctrl-C tears both down.
#
# The frontend is served as a production build by default (`next start`) so it
# works for every machine on the network. Set HAMI_DEV=1 for the hot-reload dev
# server (local use only — its HMR websocket is refused for cross-origin/LAN
# browsers). HAMI_BUILD=1 forces a rebuild before serving.
set -euo pipefail
# Job control: each `&` job gets its own process group, so `kill -- -PID`
# below tears down the whole npm -> node -> next-server tree.
set -m

cd "$(dirname "$0")"

# Load .env if present (HAMI_API_KEY generated by install.sh + any per-host
# overrides). set -a auto-exports every assignment in the sourced file so the
# Python backend picks them up.
if [ -f .env ]; then
    set -a
    # shellcheck disable=SC1091
    source .env
    set +a
fi

# Bind to 0.0.0.0 so the panel + API are reachable from the whole internal
# network, not just localhost. The installer generates a HAMI_API_KEY into
# .env so the API is auth-gated out of the box; narrow HAMI_ALLOWED_ORIGINS
# further if you need to lock things down.
export HAMI_BACKEND_HOST="${HAMI_BACKEND_HOST:-0.0.0.0}"
export HAMI_BACKEND_PORT="${HAMI_BACKEND_PORT:-8000}"
export HAMI_BACKEND_URL="${HAMI_BACKEND_URL:-http://127.0.0.1:${HAMI_BACKEND_PORT}}"
# "*" lets any LAN origin (http://<host-ip>:3000) reach the API. Safe here
# because CORS runs with allow_credentials=False and auth is header/token-based.
export HAMI_ALLOWED_ORIGINS="${HAMI_ALLOWED_ORIGINS:-*}"

PY="${PY:-python}"

"$PY" -m backend &
BACKEND_PID=$!

# Give the backend a moment to bind its port before the frontend starts.
sleep 1

if [ "${HAMI_DEV:-0}" = "1" ]; then
    # Hot-reload dev server. Fine for local work; the HMR socket won't connect
    # from other machines (Next blocks cross-origin dev endpoints).
    (cd frontend && npm run dev -- -H 0.0.0.0) &
else
    if [ ! -f frontend/.next/BUILD_ID ] || [ "${HAMI_BUILD:-0}" = "1" ]; then
        echo "==> building frontend production bundle (set HAMI_BUILD=1 to rebuild)"
        (cd frontend && npm run build)
    fi
    (cd frontend && npm run start -- -H 0.0.0.0) &
fi
FRONTEND_PID=$!

LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
echo "  frontend : http://${LAN_IP:-<host-ip>}:3000  (local: http://localhost:3000)"
echo "  backend  : http://${LAN_IP:-<host-ip>}:${HAMI_BACKEND_PORT}"

cleanup() {
    kill -- -"$BACKEND_PID" 2>/dev/null || kill "$BACKEND_PID" 2>/dev/null || true
    kill -- -"$FRONTEND_PID" 2>/dev/null || kill "$FRONTEND_PID" 2>/dev/null || true
    wait 2>/dev/null || true
}
trap cleanup EXIT INT TERM

wait
